module:
  biquad:
    left_shift:
      type: int32_t
    filter_coeffs:
      type: int32_t
      size: "5"
      attribute: DWORD_ALIGNED
    reserved:
      type: int32_t
      size: "3"
includes:
  - "stdint.h"
  - "adsp_module.h"
