module:
  parametric_eq:
    filter_coeffs:
      type: int32_t
      size: FILTERS * DSP_NUM_COEFFS_PER_BIQUAD
      attribute: DWORD_ALIGNED
includes:
  - stdint.h
  - "adsp_module.h"
defines:
  FILTERS: 4
  DSP_NUM_COEFFS_PER_BIQUAD: 5

