#pragma once

#include "dsp/biquad.h"
#include "biquad_config.h" // Autogenerated

typedef struct
{
    biquad_config_t config;
    int32_t (*filter_states)[8];
    int n_inputs;
    int n_outputs;
    int frame_size;
}biquad_state_t;

module_instance_t* biquad_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config);

void biquad_process(int32_t **input, int32_t **output, void *app_data_state);

void biquad_control(void *state, module_control_t *control);
