#pragma once

#include "biquad.h"
#include "biquad_config.h" // Autogenerated

#define MAX_CHANNELS (4)

typedef struct
{
    biquad_config_t config;
    int32_t DWORD_ALIGNED filter_states[MAX_CHANNELS][8];
}biquad_state_t;

DSP_MODULE_INIT_ATTR module_instance_t* biquad_init(uint8_t id);

DSP_MODULE_PROCESS_ATTR  void biquad_process(int32_t *input, int32_t *output, void *app_data_state, module_control_t *control);
