// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "dsp/biquad.h"
#include "biquad_config.h" // Autogenerated

#define BIQUAD_STATE_LEN (8)
typedef struct
{
    biquad_config_t config;
    int32_t **filter_states;
    int n_inputs;
    int n_outputs;
    int frame_size;
}biquad_state_t;

void biquad_init(module_instance_t* instance, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void biquad_process(int32_t **input, int32_t **output, void *app_data_state);

void biquad_control(void *state, module_control_t *control);
