// Copyright 2024-2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "dsp/signal_chain.h"
#include "blend_config.h" // Autogenerated
#include "bump_allocator.h"

typedef struct
{
    blend_config_t config;
    int n_inputs;
    int n_outputs;
    int frame_size;
    int32_t gains[2];
}blend_state_t;

#define BLEND_STAGE_REQUIRED_MEMORY 0

void blend_init(module_instance_t* instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void blend_process(int32_t **input, int32_t **output, void *app_data_state);

void blend_control(void *state, module_control_t *control);

