// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "bypass_config.h" // Autogenerated

typedef struct
{
    bypass_config_t config;
    int n_inputs;
    int n_outputs;
    int frame_size;
}bypass_state_t;

void bypass_init(module_instance_t* instance, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void bypass_process(int32_t **input, int32_t **output, void *app_data_state);

void bypass_control(void *state, module_control_t *control);
