// Copyright 2024-2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "bump_allocator.h"
#include "dsp/drc.h"
#include "compressor_sidechain_stereo_config.h" // Autogenerated

typedef struct
{
    compressor_stereo_t *comp;
    int n_inputs;
    int n_outputs;
    int frame_size;
}compressor_sidechain_stereo_state_t;

#define COMPRESSOR_SIDECHAIN_STEREO_STAGE_REQUIRED_MEMORY (sizeof(compressor_stereo_t))

void compressor_sidechain_stereo_init(module_instance_t* instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void compressor_sidechain_stereo_process(int32_t **input, int32_t **output, void *app_data_state);

void compressor_sidechain_stereo_control(void *state, module_control_t *control);
