// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "bump_allocator.h"
#include "dsp/drc.h"
#include "expander_config.h" // Autogenerated

typedef struct
{
    expander_t *ex;
    int n_inputs;
    int n_outputs;
    int frame_size;
}expander_state_t;

#define EXPANDER_STAGE_REQUIRED_MEMORY(N_IN) (N_IN * ADSP_BUMP_ALLOCATOR_DWORD_N_BYTES(sizeof(expander_t)))
#define EXPANDER_STAGE_REQUIRED_MEMORY_SLIM(N_IN) (N_IN * sizeof(expander_t))

void expander_init(module_instance_t* instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void expander_process(int32_t **input, int32_t **output, void *app_data_state);

void expander_control(void *state, module_control_t *control);
