#pragma once

#include "dsp/drc.h"
#include "limiter_peak_config.h" // Autogenerated

#define MAX_CHANNELS (4)
typedef struct
{
    limiter_t lim;
    int n_inputs;
    int n_outputs;
    int frame_size;
}limiter_peak_state_t;

module_instance_t* limiter_peak_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config);

void limiter_peak_process(int32_t **input, int32_t **output, void *app_data_state);

void limiter_peak_control(void *state, module_control_t *control);
