// Copyright 2024-2026 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#pragma once

#include "dsp/signal_chain.h"
#include "router_4to1_config.h" // Autogenerated
#include "bump_allocator.h"

typedef struct
{
    router_4to1_config_t config;
    int n_inputs;
    int n_outputs;
    int frame_size;
} router_4to1_state_t;

#define ROUTER_4TO1_STAGE_REQUIRED_MEMORY 0

void router_4to1_init(module_instance_t* instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size);

void router_4to1_process(int32_t **input, int32_t **output, void *app_data_state);

void router_4to1_control(void *state, module_control_t *control);
