#pragma once

#include "sum_config.h" // Autogenerated

typedef struct
{
    sum_config_t config;
    int n_inputs;
    int n_outputs;
    int frame_size;
    int n_per_sum;  // n_inputs / n_outputs
}sum_state_t;

module_instance_t* sum_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config);

void sum_process(int32_t **input, int32_t **output, void *app_data_state);

void sum_control(void *state, module_control_t *control);
