// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/buffer.h"

void buffer_process(int32_t ** input, int32_t ** output, void * app_data_state)
{
    xassert(app_data_state != NULL);
    buffer_state_t *state = app_data_state;

    int32_t* d = &output[0][0];
    // int32_t overlap = state->buffer[0].buffer_len - state->frame_size;
    printf("D addr: %p\n", d);
    // roll buffer
    // printf("rolling buffer by %d\n", state->frame_size);
    memcpy(d, state->buffer->overlap_data, state->overlap_len*sizeof(int32_t));

    // add new samples
    int32_t* samples_in = input[0];
    memcpy(d + state->overlap_len, samples_in, state->frame_size*sizeof(int32_t));

    // update saved overlap samples
    memcpy(state->buffer->overlap_data, d + state->frame_size, state->overlap_len*sizeof(int32_t));

}

void buffer_init(module_instance_t* instance,
                adsp_bump_allocator_t* allocator,
                uint8_t id,
                int n_inputs,
                int n_outputs,
                int frame_size)
{
    xassert(n_inputs == 1 && "buffer should have the same number of inputs and outputs");
    buffer_state_t *state = instance->state;
    buffer_constants_t* constants = instance->constants;

    memset(state, 0, sizeof(buffer_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;
    state->buffer_len = constants->buffer_len;
    state->overlap_len = state->buffer_len - state->frame_size;

    state->buffer = ADSP_BUMP_ALLOCATOR_WORD_ALLIGNED_MALLOC(allocator, n_inputs * sizeof(buffer_t));

    // make the buffer DWORD aligned for FFT
    state->buffer->overlap_data = ADSP_BUMP_ALLOCATOR_WORD_ALLIGNED_MALLOC(allocator, state->overlap_len * sizeof(int32_t));
    printf("buff mem addr: %p\n", state->buffer->overlap_data);
}

void buffer_control(void *state, module_control_t *control)
{
    // FIR cannot be updated, it must be set at init
}
