// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/bypass.h"

void bypass_process(int32_t **input, int32_t **output, void *app_data_state)
{
    bypass_state_t *state = app_data_state;

    // do while saves instructions for cases
    // where the loop will always execute at
    // least once
    int i = 0;
    do {
        int32_t *in = input[i];
        int32_t *out = output[i];
        memcpy(out, in, sizeof(int32_t) * state->frame_size);
    } while (++i < state->n_outputs);
}

module_instance_t* bypass_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config)
{
    module_instance_t *module_instance = malloc(sizeof(module_instance_t));

    bypass_state_t *state = malloc(sizeof(bypass_state_t)); // malloc_from_heap
    bypass_config_t *config = malloc(sizeof(bypass_config_t)); // malloc_from_heap

    memset(state, 0, sizeof(bypass_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    if(module_config != NULL)
    {
        bypass_config_t *init_config = module_config;
        memcpy(&state->config, init_config, sizeof(bypass_config_t));
    }
    else
    {
        state->config = (bypass_config_t){ 0 };
    }

    memcpy(config, &state->config, sizeof(bypass_config_t));

    module_instance->state = state;

    // Control stuff
    module_instance->control.config = config;
    module_instance->control.id = id;
    module_instance->control.module_type = e_dsp_stage_bypass;
    module_instance->control.num_control_commands = NUM_CMDS_BYPASS;
    module_instance->control.config_rw_state = config_none_pending;
    return module_instance;
}

void bypass_control(void *module_state, module_control_t *control)
{
    // nothing to do
}
