// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/bypass.h"

void bypass_process(int32_t **input, int32_t **output, void *app_data_state)
{
    bypass_state_t *state = app_data_state;

    // do while saves instructions for cases
    // where the loop will always execute at
    // least once
    int i = 0;
    do {
        int32_t *in = input[i];
        int32_t *out = output[i];
        memcpy(out, in, sizeof(int32_t) * state->frame_size);
    } while (++i < state->n_outputs);
}

void bypass_init(module_instance_t* module_instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size)
{
    bypass_state_t *state =module_instance->state;
    bypass_config_t *config = module_instance->control.config;

    memset(state, 0, sizeof(bypass_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    memcpy(&state->config, config, sizeof(bypass_config_t));
}

void bypass_control(void *module_state, module_control_t *control)
{
    // nothing to do
}
