// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/dsp_thread.h"

module_instance_t* dsp_thread_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config)
{
    module_instance_t *module_instance = malloc(sizeof(module_instance_t));

    dsp_thread_state_t *state = malloc(sizeof(dsp_thread_state_t));
    dsp_thread_config_t *config = malloc(sizeof(dsp_thread_config_t));

    memset(state, 0, sizeof(dsp_thread_state_t));

    config->max_cycles = 0;

    module_instance->state = state;

    // Control stuff
    module_instance->control.config = config;
    module_instance->control.id = id;
    module_instance->control.module_type = e_dsp_stage_dsp_thread;
    module_instance->control.num_control_commands = NUM_CMDS_DSP_THREAD;
    module_instance->control.config_rw_state = config_none_pending;
    return module_instance;
}

void dsp_thread_control(void *module_state, module_control_t *control)
{
    dsp_thread_state_t *state = module_state;
    dsp_thread_config_t *config = control->config;

    if(control->config_rw_state == config_write_pending)
    {
        // No write commands for the dsp_thread stage
        control->config_rw_state = config_none_pending;
    }
    else if(control->config_rw_state == config_read_pending)
    {
        config->max_cycles = state->max_cycles;
        control->config_rw_state = config_read_updated;
    }
}
