
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "dummy_parametric_eq.h"
#include "cmds.h" // Autogenerated


DSP_MODULE_PROCESS_ATTR
void parametric_eq_process(int32_t **input, int32_t **output, void *app_data_state)
{
    xassert(app_data_state != NULL);
    parametric_eq_state_t *state = app_data_state;
    int32_t *in = (int32_t*)input;
    int32_t *out = (int32_t*)output;

    // 4 biquads over 4 samples take 290 reference timer cycles
    for(int i=0; i<state->n_outputs; i++)
    {
        for(int j=0; j<state->frame_size; j++)
        {
            *out++ = *in++;
            // We don't want to include lib_dsp
            /*output[i] = dsp_filters_biquads (( int32_t ) input[i + state->config.input_start_offset],
                                                            state->config.filter_coeffs ,
                                                            state->filter_states[i],
                                                            FILTERS ,
                                                            28);*/
        }
    }
}


DSP_MODULE_INIT_ATTR
module_instance_t* parametric_eq_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config)
{
    module_instance_t *module_instance = malloc(sizeof(module_instance_t));

    parametric_eq_state_t *state = malloc(sizeof(parametric_eq_state_t)); // malloc_from_heap
    parametric_eq_config_t *config = malloc(sizeof(parametric_eq_config_t)); // malloc_from_heap

    memset(&state, 0, sizeof(parametric_eq_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    if(module_config != NULL)
    {
        parametric_eq_config_t *init_config = module_config;
        memcpy(&state->config, init_config, sizeof(parametric_eq_config_t));
    }

    memcpy(config, &state->config, sizeof(parametric_eq_config_t));

    module_instance->state = state;
    module_instance->process_sample = parametric_eq_process;

    // Control stuff
    module_instance->module_control = parametric_eq_control;
    module_instance->control.config = config;
    module_instance->control.id = id;
    module_instance->control.module_type = parametric_eq;
    module_instance->control.num_control_commands = NUM_CMDS_PARAMETRIC_EQ;
    module_instance->control.config_rw_state = config_none_pending;
    return module_instance;
}

DSP_MODULE_CONTROL_ATTR
void parametric_eq_control(void *module_state, module_control_t *control)
{
    xassert(module_state != NULL);
    parametric_eq_state_t *state = module_state;
    xassert(control != NULL);
    parametric_eq_config_t *config = control->config;

    if(control->config_rw_state == config_write_pending)
    {
        // Finish the write by updating the working copy with the new config
        memcpy(&state->config, config, sizeof(parametric_eq_config_t));
        control->config_rw_state = config_none_pending;
    }
    else if(control->config_rw_state == config_read_pending)
    {
        memcpy(config, &state->config, sizeof(parametric_eq_config_t));
        control->config_rw_state = config_read_updated;
    }
}
