// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/fft.h"
#include "dsp/defines.h"

void fft_process(int32_t ** input, int32_t ** output, void * app_data_state)
{
    xassert(app_data_state != NULL);
    fft_state_t *state = app_data_state;

    // FFT is inplace, so might as well do it in the new place
    if(input != output) {
        memcpy(&output[0][sizeof(bfp_complex_s32_t)], &input[0][0], state->nfft*sizeof(int32_t));
    }
    // note calc headroom as we may h
    bfp_s32_t* in_sig = (bfp_s32_t*) &output[0][0];

    bfp_s32_init(in_sig, &output[0][sizeof(bfp_complex_s32_t)], SIG_EXP, state->nfft, 1);
    printf("in_sig exp: %d hr %u\n", in_sig->exp, in_sig->hr);

    // do the FFT, note out_spect = (bfp_complex_s32_t*)in_sig
    bfp_complex_s32_t * out_spect = bfp_fft_forward_mono(in_sig);
    bfp_fft_unpack_mono(out_spect);
    printf("spect exp: %d hr %u, sz %u\n", out_spect->exp, out_spect->hr, out_spect->length);

    // bfp_complex_s32_use_exponent(out_spect, state->exp);
    // printf("newspect exp: %d hr%u\n", c->exp, c->hr);

    // output[0] = (int32_t*)c->data;

}

void fft_init(module_instance_t* instance,
                adsp_bump_allocator_t* allocator,
                uint8_t id,
                int n_inputs,
                int n_outputs,
                int frame_size)
{
    xassert(n_inputs == 1 && "fft should have the same number of inputs and outputs");
    fft_state_t *state = instance->state;
    fft_constants_t* constants = instance->constants;

    memset(state, 0, sizeof(fft_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    state->nfft = constants->nfft;
    state->exp = constants->exp;

}

void fft_control(void *state, module_control_t *control)
{
    // FIR cannot be updated, it must be set at init
}
