// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/fft.h"
#include "dsp/defines.h"

void fft_process(int32_t ** input, int32_t ** output, void * app_data_state)
{
    xassert(app_data_state != NULL);
    fft_state_t *state = app_data_state;

    // note calc headroom as we may h
    bfp_s32_t in_sig;
    bfp_s32_init(&in_sig, &input[0][0], SIG_EXP, state->nfft, 1);

    // do the FFT
    bfp_complex_s32_t * c = bfp_fft_forward_mono(&in_sig);

    bfp_complex_s32_use_exponent(c, state->exp);

    // output[0] = (int32_t*)c->data;
    if(input != output) {
        memcpy(output[0], c->data, state->nfft*sizeof(int32_t));
    }
}

void fft_init(module_instance_t* instance,
                adsp_bump_allocator_t* allocator,
                uint8_t id,
                int n_inputs,
                int n_outputs,
                int frame_size)
{
    xassert(n_inputs == 1 && "fft should have the same number of inputs and outputs");
    fft_state_t *state = instance->state;
    fft_constants_t* constants = instance->constants;

    memset(state, 0, sizeof(fft_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    state->nfft = constants->nfft;
    state->exp = constants->exp;

}

void fft_control(void *state, module_control_t *control)
{
    // FIR cannot be updated, it must be set at init
}
