// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/ifft.h"
#include "dsp/defines.h"

void ifft_process(int32_t ** input, int32_t ** output, void * app_data_state)
{
    xassert(app_data_state != NULL);
    ifft_state_t *state = app_data_state;

    // initialise BFP spectrum, note length = nfft/2 as packed complex numbers
    bfp_complex_s32_t in_spect;
    bfp_complex_s32_init(&in_spect, (complex_s32_t*)&input[0][0], state->exp, state->nfft >> 1, 1);

    // do the ifft
    bfp_s32_t *out_sig = bfp_fft_inverse_mono(&in_spect);

    // return to Q_SIG format
    bfp_s32_use_exponent(out_sig, SIG_EXP);

    // if input and output pointer are different, copy
    if(input != output) {
        memcpy(&output[0][0], &(input[0][0]), state->nfft*sizeof(int32_t));
    }
}

void ifft_init(module_instance_t* instance,
                adsp_bump_allocator_t* allocator,
                uint8_t id,
                int n_inputs,
                int n_outputs,
                int frame_size)
{
    xassert(n_inputs == 1 && "ifft should have the same number of inputs and outputs");
    ifft_state_t *state = instance->state;
    ifft_constants_t* constants = instance->constants;

    memset(state, 0, sizeof(ifft_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    state->nfft = constants->nfft;
    state->exp = constants->exp;
}

void ifft_control(void *state, module_control_t *control)
{
    // FIR cannot be updated, it must be set at init
}
