#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/limiter_peak.h"

static inline void limiter_copy_config_to_state(limiter_t *lim_state, int n_inputs, const limiter_peak_config_t *lim_config)
{
    // Same config for all channels
    for(int i=0; i<n_inputs; i++)
    {
        lim_state[i].env_det.attack_alpha = lim_config->attack_alpha;
        lim_state[i].env_det.release_alpha = lim_config->release_alpha;
        lim_state[i].threshold = lim_config->threshold;
    }
}

static inline void limiter_copy_state_to_config(limiter_peak_config_t *lim_config, const limiter_t *lim_state)
{
    // Copy from channel 0 state to the config
    lim_config->attack_alpha = lim_state[0].env_det.attack_alpha;
    lim_config->release_alpha = lim_state[0].env_det.release_alpha;
    lim_config->envelope = lim_state[0].env_det.envelope;
    lim_config->gain = lim_state[0].gain;
    lim_config->threshold = lim_state[0].threshold;
}

void limiter_peak_process(int32_t **input, int32_t **output, void *app_data_state)
{
    xassert(app_data_state != NULL);
    limiter_peak_state_t *state = app_data_state;

    // do while saves instructions for cases
    // where the loop will always execute at
    // least once
    int i = 0;
    do {
        int32_t *in = input[i];
        int32_t *out = output[i];

        int j = 0;
        do {
            *out++ = adsp_limiter_peak(&state->lim[i], *in++);
        } while(++j < state->frame_size);
    } while(++i < state->n_outputs);
}

module_instance_t* limiter_peak_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config)
{
    module_instance_t *module_instance = malloc(sizeof(module_instance_t));

    limiter_peak_state_t *state = malloc(sizeof(limiter_peak_state_t)); // malloc_from_heap
    limiter_peak_config_t *config = malloc(sizeof(limiter_peak_config_t)); // malloc_from_heap

    memset(state, 0, sizeof(limiter_peak_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    state->lim = malloc(state->n_inputs * sizeof(limiter_t));
    memset(state->lim, 0, state->n_inputs * sizeof(limiter_t));

    for(int i=0; i<state->n_inputs; i++)
    {
        state->lim.gain = 1;
        state->lim.env_det.envelope = 0;
    }

    xassert(module_config != NULL);

    limiter_peak_config_t *init_config = module_config;
    limiter_copy_config_to_state(state->lim, state->n_inputs, init_config);

    limiter_copy_state_to_config(config, state->lim);

    module_instance->state = state;

    // Control stuff
    module_instance->control.config = config;
    module_instance->control.id = id;
    module_instance->control.module_type = e_dsp_stage_limiter_peak;
    module_instance->control.num_control_commands = NUM_CMDS_LIMITER_PEAK;
    module_instance->control.config_rw_state = config_none_pending;
    return module_instance;
}

void limiter_peak_control(void *module_state, module_control_t *control)
{
    xassert(module_state != NULL);
    limiter_peak_state_t *state = module_state;
    xassert(control != NULL);
    limiter_peak_config_t *config = control->config;

    if(control->config_rw_state == config_write_pending)
    {
        // Finish the write by updating the working copy with the new config
        // TODO update only the fields written by the host
        limiter_copy_config_to_state(state->lim, state->n_inputs, config);
        control->config_rw_state = config_none_pending;
    }
    else if(control->config_rw_state == config_read_pending)
    {
        limiter_copy_state_to_config(config, state->lim);
        control->config_rw_state = config_read_updated;
    }
}
