// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/reverb.h"

void reverb_init(module_instance_t* instance,
                 adsp_bump_allocator_t* allocator,
                 uint8_t id,
                 int n_inputs,
                 int n_outputs,
                 int frame_size)
{
    xassert(n_inputs == n_outputs && "Biquad should have the same number of inputs and outputs");
    reverb_state_t *state = instance->state;
    reverb_config_t *config = instance->control.config;

    memcpy(&state->config, config, sizeof(reverb_config_t));

    memset(state, 0, sizeof(reverb_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    uint32_t n_chans = n_inputs;
    float const fs = 48000;
    float const max_room_size = 1.0;
    float const room_size = 1.0;
    float const decay = 1.0;
    float const damping = 1.0;
    float const wet_gain_db = -1.0;
    float const dry_gain_db = -1.0;
    float const pregain = 0.015;

    xassert(n_inputs <= MAX_CHANS);

    uint32_t sz = RV_HEAP_SZ(48000, 1.0f);
    uint8_t *reverb_heap = malloc(sz);
    memset(reverb_heap, 0, sz);

    state->reverb_room = adsp_reverb_room_init(n_chans, fs,
                                max_room_size, room_size,
                                decay, damping, wet_gain_db,
                                dry_gain_db, pregain,
                                reverb_heap);
}

void reverb_process(int32_t **input, int32_t **output, void *app_data_state)
{
    reverb_state_t *state = app_data_state;
    int i = 0;
    do {
        int32_t *in = input[i];
        int32_t *out = output[i];
        int j = 0;
        do
        {
            *out++ = adsp_reverb_room(&state->reverb_room, (*in++), i);
        } while (++j < state->frame_size);
    } while (++i < state->n_outputs);
}

void reverb_control(void *state, module_control_t *control)
{

}
