// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/reverb.h"

void reverb_init(module_instance_t* instance,
                 adsp_bump_allocator_t* allocator,
                 uint8_t id,
                 int n_inputs,
                 int n_outputs,
                 int frame_size)
{
    xassert(n_inputs == n_outputs && "Reverb should have the same number of inputs and outputs");
    reverb_state_t *state = instance->state;
    reverb_config_t *config = instance->control.config;

    memset(state, 0, sizeof(reverb_state_t));
    memcpy(&state->config, config, sizeof(reverb_config_t));

    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    uint32_t n_chans = n_inputs;
    float fs = state->config.sampling_freq;
    float max_room_size = state->config.max_room_size;

    float const room_size = state->config.room_size;
    float const decay = state->config.decay;
    float const damping = state->config.damping;
    float const wet_gain_db = state->config.wet_gain;
    float const dry_gain_db = state->config.dry_gain_db;
    float const pregain = state->config.pregain;

    // Both fs and max_room_size are used in heap memory calculation, which is currently defined at compile time
    // #define REVERB_REQUIRED_MEMORY(N_IN, N_OUT, FRAME_SIZE) (RV_HEAP_SZ(48000, 1.0f)), so ensure the fs and max_room_size
    // we get at initialisation match.

    xassert(fs == (float)48000);
    xassert(max_room_size == (float)1);

    xassert(n_inputs == 1); // Currently support only 1 channel reverb
    xassert(n_inputs <= MAX_CHANS);

    uint32_t sz = RV_HEAP_SZ(fs, max_room_size);
    uint8_t *reverb_heap = adsp_bump_allocator_malloc(allocator, sz);
    memset(reverb_heap, 0, sz);

    state->reverb_room = adsp_reverb_room_init(n_chans, fs,
                                max_room_size, room_size,
                                decay, damping, wet_gain_db,
                                dry_gain_db, pregain,
                                reverb_heap);
}

void reverb_process(int32_t **input, int32_t **output, void *app_data_state)
{
    reverb_state_t *state = app_data_state;
    int i = 0;
    do {
        int32_t *in = input[i];
        int32_t *out = output[i];
        int j = 0;
        do
        {
            *out++ = adsp_reverb_room(&state->reverb_room, (*in++), i);
        } while (++j < state->frame_size);
    } while (++i < state->n_outputs);
}

void reverb_control(void *module_state, module_control_t *control)
{
    xassert(module_state != NULL);
    reverb_state_t *state = module_state;
    xassert(control != NULL);
    reverb_config_t *config = control->config;

    if(control->config_rw_state == config_write_pending)
    {
        // Finish the write by updating the working copy with the new config
        memcpy(&state->config, config, sizeof(reverb_config_t));
        control->config_rw_state = config_none_pending;
    }
    else if(control->config_rw_state == config_read_pending)
    {
        memcpy(config, &state->config, sizeof(reverb_config_t));
        control->config_rw_state = config_read_updated;
    }
    else {
        // nothing to do
    }

}
