// Copyright 2024-2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/router_4to1.h"

void router_4to1_process(int32_t **input, int32_t **output, void *app_data_state)
{
    router_4to1_state_t *state = app_data_state;

    for(int sample_index = 0; sample_index < state->frame_size; ++sample_index) {
        int32_t input_samples[4];
        
        // Get input samples for the current sample index
        for(int i = 0; i < 4; i++) {
            if (i < state->n_inputs) {
                input_samples[i] = input[i][sample_index];
            } else {
                input_samples[i] = 0; // Zero-pad if fewer than 4 inputs
            }
        }
        
        // Process through the router
        output[0][sample_index] = adsp_router_4to1(&(state->config.channel_states[0]), input_samples);
    }
}

void router_4to1_init(module_instance_t* instance, adsp_bump_allocator_t* allocator, uint8_t id, int n_inputs, int n_outputs, int frame_size)
{
    router_4to1_state_t *state = instance->state;
    router_4to1_config_t *config = instance->control.config;

    memset(state, 0, sizeof(router_4to1_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;
    xassert(n_outputs == 1 && "Router 4:1 should only have one output");
    xassert(n_inputs <= 4 && "Router 4:1 cannot have more than 4 inputs");

    memcpy(&state->config, config, sizeof(router_4to1_config_t));

}

void router_4to1_control(void *module_state, module_control_t *control)
{
    router_4to1_state_t *state = module_state;
    router_4to1_config_t *config = control->config;

    if(control->config_rw_state == config_write_pending)
    {
        // Finish the write by updating the working copy with the new config
        memcpy(&state->config, config, sizeof(router_4to1_config_t));
    
        control->config_rw_state = config_none_pending;
    }
}
