#include <string.h>
#include <stdlib.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/sum.h"

#include <print.h>

void sum_process(int32_t **input, int32_t **output, void *app_data_state)
{
    sum_state_t *state = app_data_state;

    int input_idx = 0;
    for(int output_idx = 0; output_idx < state->n_outputs; ++ output_idx) {
        int32_t* out = output[output_idx];
        for(int frame_idx = 0; frame_idx < state->frame_size; ++frame_idx) {
            out[frame_idx] = input[input_idx][frame_idx];
        }
        input_idx += 1;

        for(int i = 1; i < state->n_per_sum; ++i) {
            for(int frame_idx = 0; frame_idx < state->frame_size; ++frame_idx) {
                out[frame_idx] += input[input_idx][frame_idx];
            }
            input_idx += 1;
        }
    }
}

module_instance_t* sum_init(uint8_t id, int n_inputs, int n_outputs, int frame_size, void* module_config)
{
    module_instance_t *module_instance = malloc(sizeof(module_instance_t));

    sum_state_t *state = malloc(sizeof(sum_state_t)); // malloc_from_heap
    sum_config_t *config = malloc(sizeof(sum_config_t)); // malloc_from_heap

    memset(state, 0, sizeof(sum_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;
    state->n_per_sum = n_inputs / n_outputs;
    xassert(n_inputs % n_outputs == 0); // must be able to sum all the inputs

    if(module_config != NULL)
    {
        sum_config_t *init_config = module_config;
        memcpy(&state->config, init_config, sizeof(sum_config_t));
    }
    else
    {
        state->config = (sum_config_t){ 0 };
    }

    memcpy(config, &state->config, sizeof(sum_config_t));

    module_instance->state = state;

    // Control stuff
    module_instance->control.config = config;
    module_instance->control.id = id;
    module_instance->control.module_type = e_dsp_stage_sum;
    module_instance->control.num_control_commands = NUM_CMDS_SUM;
    module_instance->control.config_rw_state = config_none_pending;
    return module_instance;
}

void sum_control(void *module_state, module_control_t *control)
{
    // nothing to do
}
