// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <xcore/assert.h>
#include <debug_print.h>
#include "cmds.h" // Autogenerated
#include "cmd_offsets.h" // Autogenerated
#include "stages/wola_rect.h"

void wola_rect_process(int32_t *** input, int32_t ** output, void * app_data_state)
{
    xassert(app_data_state != NULL);
    wola_rect_state_t *state = app_data_state;
    // just point to the start of the valid data, length should just work out
    
    // printf("wola start: %p\n", &input[0][0][0]);
    // printf("win start: %p\n", &input[0][0][state->win_start]);
    // printf("wola out: %p\n", &output[0][0]);

    memcpy(&output[0][0], &(input[0][0][state->win_start]), state->frame_size);
}


void wola_rect_init(module_instance_t* instance,
                adsp_bump_allocator_t* allocator,
                uint8_t id,
                int n_inputs,
                int n_outputs,
                int frame_size)
{
    xassert(n_inputs == 1 && "wola_rect should have the same number of inputs and outputs");
    wola_rect_state_t *state = instance->state;
    wola_rect_constants_t* constants = instance->constants;

    memset(state, 0, sizeof(wola_rect_state_t));
    state->n_inputs = n_inputs;
    state->n_outputs = n_outputs;
    state->frame_size = frame_size;

    // point to shared memory
    state->win_start = constants->win_start;
}

void wola_rect_control(void *state, module_control_t *control)
{
    // FIR cannot be updated, it must be set at init
}
