# The following patterns are to be excluded from the documentation build

**CHANGELOG*
**LICENSE*

# Readmes
examples/app_simple_audio_dsp_integration/README.rst
host/dsp_host/README.rst
test/biquad/README.rst

.doc_venv/*
test/*
build/*

# Do not build .md files
*.md
**/*.md

# Do not build the app docs
tools/*

# Don't include libraries in user docs

# Ignore additional licence file
ADDITIONAL_LICENSES.rst
