

.. _The XMOS XS3 Architecture: https://www.xmos.com/download/The-XMOS-XS3-Architecture.pdf
.. _XCORE Math Library: https://www.xmos.com/file/lib_xcore_math/
.. _SciPy/filter_design : https://docs.scipy.org/doc/scipy/reference/signal.html#filter-design>
.. _Jupyter Notebook : https://jupyter.org/
.. _XK-EVK-XU316 : https://www.xmos.com/xk-evk-xu316
.. _XK-316-AUDIO-MC-AB : https://www.xmos.com/xk-audio-316-mc-ab
