[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audio_dsp"
version = "0.1.0"
description = "An audio DSP library for the xcore"
authors = [
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "soundfile",
    "IPyWidgets",
    "graphviz",
    "IPython",
    "pyyaml",
    "mako",
    "tabulate"
]

[tool.black]
line-length = 99

